SRC1 = Person.cpp SortPersons.cpp
EXE1 = SortPersons.exe
SRC2 = Palindrome.cpp
EXE2 = Palindrome.exe
SRC3 = TestFunctionPointer.cpp
EXE3 = TestFunctionPointer.exe

sortpersons:
	g++ ${SRC1} -o ${EXE1}
	./${EXE1}

palindrome:
	g++ ${SRC2} -o ${EXE2}
	./${EXE2}

testfp:
	g++ ${SRC3} -o ${EXE3}
	./${EXE3}

