#Makefile for Lab 5

CPP = testMain.cpp Employee.cpp Staff.cpp Education.cpp Faculty.cpp Parttime.cpp Date.cpp
MAIN = testMain.exe

all:
	g++ ${CPP} -o ${MAIN} 

clean:
	rm -f ${MAIN}

.PHONY:
	all clean
