SRC1 = Polar.cpp Cartesian.cpp PolarTest.cpp 
EXE1 = PolarTest.exe
SRC2 = SafeArray.cpp SafeArrayTest.cpp
EXE2 = SafeArrayTest.exe

polar:
	g++ ${SRC1} -o ${EXE1}
	./${EXE1}

safearray:
	g++ ${SRC2} -o ${EXE2}
	./${EXE2}

.PHONY:
	polar